

#SUBSETTING 

```{r}
library(plyr)


set.seed(123435)
X= data.frame("var1" = sample(1:5), "var2" = sample(6:10), "var3"= sample(11:15))

X = X[sample(1:5),];

X$var2[c(1,3)]=NA

print(X)
```


```{r}
X[,1] #JUST FIRST COLUMN
X[,"var1"]

X[1:2, "var2"] #First two rows of var2


X[X$var1<= 3 & X$var3 > 11, ]  #USAR BOOLEANOS PARA SACAR EN ESTE CASO LAS FILAS DESEADAS 

X[which(X$var2>8),]  #MISMO PERO SIN NA 

X$var4 = rnorm(5)  #PARA AGREGAR COLUMNA






```



#SUMMARIZING DATA

```{r}
# head()
#tail()
#summary

#table(restData$councilDistrict, restData$zipCode)

#colSums()

# restData[restData$zipCode %in% c(21212, 212123)]


```



```{r}
library(datasets)

df= as.data.frame(UCBAdmissions)

summary(df)

#CROSS TABS
xt= xtabs(Freq ~ Gender + Admit, data= df )
xt 
```


#CREATING NEW VARIABLES 
often the data wont have a value that you are looking for 
```{r}

```



#RESHAPING DATA
```{r}
library(datasets)
library(reshape2)

df= mtcars

df$carname = rownames(df)
carMelt= melt(df, id=c("carname", "gear", "cyl"), measure.vars = c("mpg", "hp"))

head(carMelt)  #VE QUE HACE

```











#DPLYR
common verbs: 
    select   
    arrange  
    filter  
    mutate   agrega variables 
    summarize

```{r}
library(dplyr)


#COMMAND PIPELINE
# USAR %>% PARA CONCATENAR COMANDOS

# chicago %>% mutate(month= as.POSIXlt(date)$mon +1) %>% group_by(month) %>% summarize(pm25 = mean(pm25), o3= max(o3mean2)) 

```





# MERGING DATA

```{r}
if (!file.exists("./data")){dir.create("./data")}
url= "https://raw.githubusercontent.com/DataScienceSpecialization/courses/master/03_GettingData/04_01_editingTextVariables/data/reviews.csv"
url2= "https://raw.githubusercontent.com/DataScienceSpecialization/courses/master/03_GettingData/04_01_editingTextVariables/data/solutions.csv"

download.file(url, destfile = "./data/reviews.csv", method = "curl")
download.file(url2, destfile = "./data/solutions.csv", method = "curl")

solutions= read.csv("./data/solutions.csv")
reviews= read.csv("./data/reviews.csv")
```

```{r}
#FIRST THING TO DO
#TO TRY TO MERGE BY COMMON NAME 


names(solutions)
names(reviews)

mergedData= merge(reviews, solutions, by.x= "solution_id", by.y="id", all= TRUE)  #By.x y By.y es para especificar que columnas se usaran para hacer el merge 

```

